name: intl_multiple_translations
description: Allow intl to support multiple translations per locale.
topics:
  - translation
  - localization
  - internationalization
  - l10n
  - i18n
version: 1.0.0
repository: https://github.com/zeezooz/intl_multiple_translations

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <0.20.0"

dev_dependencies:
  test: ^1.17.12
